apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
  namespace: production
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: YWNhZGVteQ==  # "academy" codificado en base64
  MYSQL_USER_PASSWORD: TUlHQVNFY2hhcnQxMjM=  # "MIGASEchart123" codificado en base64