apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-deployment
  namespace: production
spec:
  replicas: 3
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service
        image: mramoscli/order-service:latest  # Reemplaza "<tu_usuario_docker>" con tu usuario de Docker Hub
        ports:
        - containerPort: 8081
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://mysql-service:3306/orderdb
        - name: SPRING_DATASOURCE_USERNAME
          value: root
        - name: SPRING_DATASOURCE_PASSWORD
          value: academy
        - name: SPRING_JPA_HIBERNATE_DDL_AUTO
          value: update
        - name: FEIGN_HYSTRIX_ENABLED
          value: "true"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"