apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
  namespace: production
spec:
  replicas: 3
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: mramoscli/user-service:latest  # Reemplaza "<tu_usuario_docker>" con tu usuario de Docker Hub
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://mysql-service:3306/userdb
        - name: SPRING_DATASOURCE_USERNAME
          value: root
        - name: SPRING_DATASOURCE_PASSWORD
          value: academy
        - name: SPRING_JPA_HIBERNATE_DDL_AUTO
          value: update
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"