apiVersion: v1
kind: Service
metadata:
  name: order-service-nodeport
  namespace: production
spec:
  selector:
    app: order-service
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30081  # Puedes elegir cualquier puerto dentro del rango permitido (30000-32767)
  type: NodePort