apiVersion: v1
kind: Service
metadata:
  name: user-service-nodeport
  namespace: production
spec:
  selector:
    app: user-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080  # Puedes elegir cualquier puerto dentro del rango permitido (30000-32767)
  type: NodePort